import { Stack } from "expo-router";
import React from "react";
import { StatusBar } from "react-native";

export default function RootLayout() {
    return (
        <>
            <Stack screenOptions={{ headerShown: false }}>
                <Stack.Screen name="index" />
                <Stack.Screen name="(IntroScreens)/intro1" />
                <Stack.Screen name="(IntroScreens)/intro2" />
                <Stack.Screen name="(IntroScreens)/intro3" />
                <Stack.Screen name="(AuthScreens)/welcome" />
                <Stack.Screen name="(AuthScreens)/login" />
                <Stack.Screen name="(AuthScreens)/signup" />
                <Stack.Screen name="(AuthScreens)/ForgotPass" />
                <Stack.Screen name="(User)/FreeTrial" />
                <Stack.Screen name="(User)/Dashboard" />
                <Stack.Screen name="(User)/Gotonotifications" />
                <Stack.Screen name="(User)/CustomizedWorkout" />
                <Stack.Screen name="(User)/Dietplan" />
                <Stack.Screen name="(User)/Workoutplan" />
                <Stack.Screen name="AiScreens/Chatbot" />
                <Stack.Screen name="(User)/PaymentForm" />
                <Stack.Screen name="(User)/Contact" />
                <Stack.Screen name="(User)/GymScheduleScreen" />
                <Stack.Screen name="(User)/Profile" />
                <Stack.Screen name="(User)/AccountSettings" />
                <Stack.Screen name="(User)/UpdatePassword" />
                <Stack.Screen name="(User)/CustomizedDiet" />
                <Stack.Screen name="(User)/PersonalInfo" />
                <Stack.Screen name="(User)/WorkoutNormal" />
                <Stack.Screen name="Biceps/BarbellCurl"/>
                <Stack.Screen name="Biceps/HammerCurl"/>
                <Stack.Screen name="Biceps/ResistanceBandExt"/>
                <Stack.Screen name="Biceps/PreacherCurl"/>
                <Stack.Screen name="Biceps/InclineDumbbellCurl"/>
                <Stack.Screen name="Biceps/OverheadTricepsExtension"/>
                <Stack.Screen name="Biceps/ConcentrationCurls"/>
                <Stack.Screen name="Biceps/CloseGripBenchPress"/>
                <Stack.Screen name="Biceps/Pushdown"/>
                <Stack.Screen name="Biceps/RopePushdowns"/>
                <Stack.Screen name="Biceps/TricepDips"/>
                <Stack.Screen name="Biceps/DipsParallelBars"/>
                <Stack.Screen name="Biceps/DiamondPushUps"/>
                <Stack.Screen name="Biceps/ResistanceBandCurls"/>
                <Stack.Screen name="Biceps/WeightedChinUps"/>
                <Stack.Screen name="Biceps/SkullCrushers"/>
                <Stack.Screen name="Biceps/SpiderCurls"/>
                <Stack.Screen name="Biceps/RopeCableCurls"/>
                <Stack.Screen name="Biceps/WeightedDips"/>
                <Stack.Screen name="Biceps/ChinUps"/>
                <Stack.Screen name="Biceps/OnearmReverseGripTricep"/>
                <Stack.Screen name="(User)/DietNormal"/>
                <Stack.Screen name="Chest/BenchPress"/>
                <Stack.Screen name="Chest/InclinePress"/>
                <Stack.Screen name="Chest/DeclinePress"/>
                <Stack.Screen name="Chest/DeclineCableFly"/>
                <Stack.Screen name="Chest/DeclineDumbbellFly"/>
                <Stack.Screen name="Chest/CableCrossover"/>
                <Stack.Screen name="Chest/Burpees"/>
                <Stack.Screen name="Chest/DeclinePushUps"/>
                <Stack.Screen name="Chest/WeiDips"/>
                <Stack.Screen name="Chest/KneePushups"/>
                <Stack.Screen name="Chest/Sprint"/>
                <Stack.Screen name="Chest/DumbbellPress"/>
                <Stack.Screen name="Chest/Dips"/>
                <Stack.Screen name="Chest/InclineDumbbellFly"/>
                <Stack.Screen name="Chest/InclineDumbbellPress"/>
                <Stack.Screen name="Chest/LowCableCrossover"/>
                <Stack.Screen name="Chest/PushUps"/>
                <Stack.Screen name="Back/BentOverBarbellRow"/>
                <Stack.Screen name="Back/DumbbellBentOverRow"/>
                <Stack.Screen name="Back/FacePulls"/>
                <Stack.Screen name="Back/ChestSupportedRow"/>
                <Stack.Screen name="Back/HyperextensionsBody"/>
                <Stack.Screen name="Back/Deadlifts"/>
                <Stack.Screen name="Back/SupermanHolds"/>
                <Stack.Screen name="Back/JumpRope"/>
                <Stack.Screen name="Back/LatPullDown"/>
                <Stack.Screen name="Back/PullUps"/>
                <Stack.Screen name="Back/SingleArmDumbbellRows"/>
                <Stack.Screen name="Back/SeatedCableRow"/>
                <Stack.Screen name="Back/MountainClimbers"/>
                <Stack.Screen name="Back/WeightedPullUps"/>
                <Stack.Screen name="Back/BattleRopes"/>
                <Stack.Screen name="Back/TBar"/>
                <Stack.Screen name="Forearm/WristCurls"/>
                <Stack.Screen name="Forearm/WristRoller"/>
                <Stack.Screen name="Forearm/Barbellwristcurls"/>
                <Stack.Screen name="Forearm/ReverseDbWristCurls"/>
                <Stack.Screen name="Forearm/DeadHangs"/>
                <Stack.Screen name="Forearm/HeavyFarmerCarry"/>
                <Stack.Screen name="Forearm/ZottmanCurls"/>
                <Stack.Screen name="Forearm/TowelGripPullups"/>
                <Stack.Screen name="Legs/BarbellSquats"/>
                <Stack.Screen name="Legs/CalfRaises"/>
                <Stack.Screen name="Legs/HipThrusts"/>
                <Stack.Screen name="Legs/DumbbellSquats"/>
                <Stack.Screen name="Legs/GobletSquats"/>
                <Stack.Screen name="Legs/Hamstring"/>
                <Stack.Screen name="Legs/BodyweightSquats"/>
                <Stack.Screen name="Legs/StepUpsBw"/>
                <Stack.Screen name="Legs/StepUps"/>
                <Stack.Screen name="Legs/KettlebellSwings"/>
                <Stack.Screen name="Legs/KettlebellSquats"/>
                <Stack.Screen name="Legs/BoxJumps"/>
                <Stack.Screen name="Legs/HackSquat"/>
                <Stack.Screen name="Legs/JumpSquats"/>
                <Stack.Screen name="Legs/BulgarianSquats"/>
                <Stack.Screen name="Legs/BulgarianSquatsBW"/>
                <Stack.Screen name="Legs/WalkingLunges"/>
                <Stack.Screen name="Legs/StandingCalfRaises"/>
                <Stack.Screen name="Legs/RmDeadliftsDumbbell"/>
                <Stack.Screen name="Legs/LegExtensions"/>
                <Stack.Screen name="Legs/LegPress"/>
                <Stack.Screen name="Legs/Lunges"/>
                <Stack.Screen name="Shoulder/BackBarbellShrugs"/>
                <Stack.Screen name="Shoulder/CableLateralRaises"/>
                <Stack.Screen name="Shoulder/FrontRaises"/>
                <Stack.Screen name="Shoulder/BarbellShrugs"/>
                <Stack.Screen name="Shoulder/ArnoldPress"/>
                <Stack.Screen name="Shoulder/DumbbellPress"/>
                <Stack.Screen name="Shoulder/FacePulls"/>
                <Stack.Screen name="Shoulder/LateralRaises"/>
                <Stack.Screen name="Shoulder/OverheadPress"/>
                <Stack.Screen name="Shoulder/ReversePecDecMachine"/>
                <Stack.Screen name="CustomizedWorkout/BeginnerLoss"/>
                <Stack.Screen name="CustomizedWorkout/BeginnerGain"/>
                <Stack.Screen name="CustomizedWorkout/InterGain"/>
                <Stack.Screen name="CustomizedWorkout/InterLoss"/>
                <Stack.Screen name="CustomizedWorkout/ProGain"/>
                <Stack.Screen name="CustomizedWorkout/ProLoss"/>
                <Stack.Screen name="CustomizedDiet/C700"/>
                <Stack.Screen name="CustomizedDiet/C800"/>
                <Stack.Screen name="CustomizedDiet/C900"/>
                <Stack.Screen name="CustomizedDiet/C1000"/>
                <Stack.Screen name="CustomizedDiet/C1100"/>
                <Stack.Screen name="CustomizedDiet/C1200"/>
                <Stack.Screen name="CustomizedDiet/C1300"/>
                <Stack.Screen name="CustomizedDiet/C1400"/>
                <Stack.Screen name="CustomizedDiet/C1500"/>
                <Stack.Screen name="CustomizedDiet/C1600"/>
                <Stack.Screen name="CustomizedDiet/C1700"/>
                <Stack.Screen name="CustomizedDiet/C1800"/>
                <Stack.Screen name="CustomizedDiet/C1900"/>
                <Stack.Screen name="CustomizedDiet/C2000"/>
                <Stack.Screen name="CustomizedDiet/C2100"/>
                <Stack.Screen name="CustomizedDiet/C2200"/>
                <Stack.Screen name="CustomizedDiet/C2300"/>
                <Stack.Screen name="CustomizedDiet/C2400"/>
                <Stack.Screen name="CustomizedDiet/C2500"/>
                <Stack.Screen name="CustomizedDiet/C2600"/>
                <Stack.Screen name="CustomizedDiet/C2700"/>
                <Stack.Screen name="CustomizedDiet/C2800"/>
                <Stack.Screen name="CustomizedDiet/C2900"/>
                <Stack.Screen name="CustomizedDiet/C3000"/>
                <Stack.Screen name="CustomizedDiet/C3100"/>
                <Stack.Screen name="CustomizedDiet/C3200"/>
                <Stack.Screen name="CustomizedDiet/C3300"/>
                <Stack.Screen name="CustomizedDiet/C3400"/>
                <Stack.Screen name="CustomizedDiet/C3500"/>
                <Stack.Screen name="CustomizedDiet/C3600"/>
                <Stack.Screen name="CustomizedDiet/C3700"/>
                <Stack.Screen name="CustomizedDiet/C3800"/>
                <Stack.Screen name="CustomizedDiet/C3900"/>
                <Stack.Screen name="CustomizedDiet/C4000"/>
                <Stack.Screen name="CustomizedDiet/C4100"/>
                <Stack.Screen name="CustomizedDiet/C4200"/>
                <Stack.Screen name="CustomizedDiet/C4300"/>
                <Stack.Screen name="CustomizedDiet/C4400"/>
                <Stack.Screen name="CustomizedDiet/C4500"/>
                <Stack.Screen name="CustomizedDiet/C4600"/>



                
            </Stack>
            <StatusBar backgroundColor="black" />
        </>
    );
}
